### ISSUE TITLE
Pinned to kerberos==1.1.1

### ISSUE THREAD

**Issue by Daviey** [requests/requests-kerberos#37]
Hi,

I cannot see a strong reason to pin to 1.1.1.  This is causing issues, as I want to use a more recent version such as 1.1.5.  Is this specific reason required?

Thanks

**Comment by laserson** [comment]
Actually, would it be possible to move to 1.2.1, which adds py3 compatibility?

**Comment by danc86** [comment]
Just found this issue, after I filed #53 to relax the kerberos version requirement...

Please don't pin versions just because it's what you have tested. Plenty of us out here are successfully using other versions of the kerberos module :-) As mentioned already the official project is up to 1.1.5, and Fedora/RHEL are shipping 1.1 (plus various patches) and that version of the module works fine also.

The only reason to add a version requirement would be if this module relies on some interface which is not present in older versions of the dependency. Even then I would argue it should be a >= requirement only -- assume the dependency will stay compatible until proven otherwise. We just end up needing to patch out the version pinning anyway.

**Comment by mkomitee** [comment]
I'd be open to not pinning the version, but the question of whether we should use kerberos, pykerberos, or possibly python-gssapi, is another matter.

**Comment by rbcarson** [comment]
#56 switches from Apple's kerberos to non-Apple pykerberos [1.1.8, 2.0.0), which includes Python 3 support. The minimum version is set to 1.1.8 because it includes handling for string-suffixed krb5 version names, which Travis stumbled upon.
