### ISSUE TITLE
python3 and kerberos library

### ISSUE THREAD

**Issue by jamielennox** [requests/requests-kerberos#52]
The kerberos library appears essentially abandonded. Amongst other things there will be no python 3.

We should transition the library to use python-gssapi which is a higher level wrapper that uses cffi and is actively maitained. 

https://pypi.python.org/pypi/python-gssapi/
https://github.com/sigmaris/python-gssapi

**Comment by Lukasa** [comment]
We agree that we should switch, but we've been unclear on what we should be switching to: see #38.

**Comment by ASzc** [comment]
My Python 3 patch for PyKerberos was [merged](http://trac.calendarserver.org/ticket/798#comment:6) upstream a few months ago, and Apple released [kerberos 1.2.2](https://pypi.python.org/pypi/kerberos/1.2.2) on pypi, which includes it.

So, if you want to switch away from PyKerberos because of the slow updates, fair enough, but it does support Python 3 now.

**Comment by dreyco676** [comment]
I'm working on a quick and dirty port of requests-kerberos to python3 which uses PyKerberos. Is there another library I should consider instead?

**Comment by ASzc** [comment]
@dreyco676 , note that there's some ambiguity with the name PyKerberos. The original library produced by Apple is:

- called PyKerberos upstream (Issue Tracker, etc.), 
- called `kerberos` on PyPI,
- and often packaged as `python-kerberos` by Linux distros.

During the four years that PyKerberos went without an update, some unknown person uploaded a package called `pykerberos` to PyPI (with some improvements), leading a lot of people to mistake this for the original package.

Since then, the Apple version has released an update (version 1.2.2) that includes fixes, like my Python 3 patch. Since the PyPI `pykerberos` so far doesn't have a source repo or issue tracker, I would suggest staying with `kerberos`. They're only interchangeable because they're APIs happen to be the same, no other Kerberos libraries can function for requests-kerberos at the moment.

**Comment by dreyco676** [comment]
Good lord, that was really nasty to get Apple's Kerberos compiled for x64 Windows. Will that always be the case or can we get the contributors from Apple to provide some binaries?

**Comment by ASzc** [comment]
@dreyco676 It doesn't seem that Apple's maintainer (wsanchez) has much time to spare for PyKerberos, so contributions take a long time to get merged. I wouldn't expect any major improvements to happen at all without a patch being submitted.

Compiling things on Windows is generally a huge pain, but one thing that can be done on PyPI to avoid that is to provide a [wheel](http://pythonwheels.com/) archive with Windows binaries in it. Only a PyPI maintainer can upload one.

**Comment by AnthonyTruchet** [comment]
I'm using kerberos_sspi on Windows in Python3 (anaconda) thanks to pull request #55.

I'm pretty conscious the pull request #55 is not ready to be merged. Typically the python 3 fix should be split. But I submit the fix in order to have you feedback and contribute.

**Comment by rbcarson** [comment]
#56 changed the dependency on non-Windows platforms from Apple's Kerberos 1.1.1 to the [non-Apple PyKerberos](https://pypi.python.org/pypi/pykerberos), maintained by @02strich. For Windows, it'll use kerberos-sspi and pywin32 instead. I believe that these platform and library combinations support Python 3.

python-gssapi would be a more difficult transition: It's not API-compatible with (py)kerberos, I think.
