### ISSUE TITLE
Default principal: `TypeError: argument 2 must be string, not None`

### ISSUE THREAD

**Issue by gebn** [requests/requests-kerberos#76]
Python: 2.7.2
requests: 2.10.0
requests-kerberos: 0.9.0
kerberos: 1.2.4

    ...
      File "<>/common/runtime/session.py", line 38, in create
        auth=requests_kerberos.HTTPKerberosAuth())
      File "<>/requests/sessions.py", line 487, in get
        return self.request('GET', url, **kwargs)
      File "<>/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "<>/requests/sessions.py", line 591, in send
        r = dispatch_hook('response', hooks, r, **kwargs)
      File "<>/requests/hooks.py", line 31, in dispatch_hook
        _hook_data = hook(hook_data, **kwargs)
      File "<>/requests_kerberos/kerberos_.py", line 281, in handle_response
        _r = self.handle_401(response, **kwargs)
      File "<>/requests_kerberos/kerberos_.py", line 189, in handle_401
        _r = self.authenticate_user(response, **kwargs)
      File "<>/requests_kerberos/kerberos_.py", line 164, in authenticate_user
        auth_header = self.generate_request_header(response, host)
      File "<>/requests_kerberos/kerberos_.py", line 122, in generate_request_header
        gssflags=gssflags, principal=self.principal)
    TypeError: argument 2 must be string, not None

This appears to be related to the "Explicit Principal" change. I ran into it after replacing v0.8.0 with v0.9.0, and can reproduce the same behaviour in v0.10.0. Passing the principal explicitly to `HTTPKerberosAuth`'s initialiser fixes the issue, as does (in v0.10.0) replacing `kwargs['principal'] = self.principal` on line 128 of `kerberos_.py` with `pass`.

**Comment by rbcarson** [comment]
To be clear, did you get requests-kerberos using `pip install`? I ask because it seems like you're using the original Kerberos module instead of PyKerberos - the one on 02strich/pykerberos and called pykerberos on PyPI.

**Comment by behackett** [comment]
Interesting. The problem would appear to be the use of the [kerberos](https://pypi.python.org/pypi/kerberos) project instead of [pykerberos](https://pypi.python.org/pypi/pykerberos). This seems like a bug in Apple's original kerberos project, which crept in here:

http://www.calendarserver.org/changeset/13269

**Comment by gebn** [comment]
Thanks @rbcarson and @behackett. You're both correct - swapping out `kerberos-1.2.4` for `pykerberos-1.1.9` fixes the issue. That'll teach me to read dependencies more carefully.

**Comment by rbcarson** [comment]
Thanks for tracking this down, @behackett - looks like it was because the format string changed from `s|zl` to `s|slO` for `PyArg_ParseTupleAndKeywords`.

The confusing names and conflicting namespace of Apple's Kerberos and PyKerberos is a recurring pain point, unfortunately.

**Comment by sparkvilla** [comment]
Hi all. I have a related issue. I am using kerberos auth as ansible winrm transport and when trying to run a simple ping command I get an error of this type:

    "kerberos: argument 2 must be string, not None"

Executing this command:
# pip list | grep -i kerberos
kerberos (1.2.4)
pykerberos (1.1.13)
requests-kerberos (0.10.0)

How could I solve this? How to swap  kerberos for pykerberos?

**Comment by rbcarson** [comment]
@sparkvilla I think the solution is to uninstall kerberos and keep pykerberos. Would that work for you?

**Comment by sparkvilla** [comment]
@rbcarson keeping pykerberos and uninstalling kerberos worked for me. Thank you!

**Comment by lupuswere** [comment]
Removing kerberos doesn't work for me, right now I'm commenting out line 128 `kwargs['principal'] = self.principal` of `kerberos_.py` to unblock my development. Anyone could help me out? Thanks!

My kerberos versions:
pip list | grep -i kerberos
kerberos (1.2.2)
pykerberos (1.1.13)
requests-kerberos (0.10.0)
urllib2-kerberos (0.1.6)

**Comment by rbcarson** [comment]
Unfortunately, kerberos and pykerberos claim the same module name
'kerberos', so if you have both installed, the most recently installed one
probably overwrote the old one. Please double-check that that `import
kerberos` is actually pykerberos.

**Comment by behackett** [comment]
Note that this problem was finally fixed in Apple's project 5 days ago, though no related release yet:

https://github.com/apple/ccs-pykerberos/commit/a47bac77a5d5176143c0b97d5d7f70d6417865a3

**Comment by behackett** [comment]
@rbcarson maybe requests-kerberos should try to detect if Apple's kerberos is installed and raise an exception (I know, how to tell...)? The problem isn't just API inconsistencies. Apple's project requires the use of authGSSClientClean to destroy context objects or you end up leaking memory.

**Comment by rbcarson** [comment]
@behackett The easiest way is to ask @02strich to cut a new release that
contains a symbol we could check. But I am conflicted about this because
ideally we would be depending on Apple Kerberos, and there have been Linux
distribution maintainers who have taken issue with the dependency on
PyKerberos.

On Tue, Oct 18, 2016, 16:24 Bernie Hackett, <notifications@github.com>
wrote:

@rbcarson <https://github.com/rbcarson> maybe requests-kerberos should try
to detect if Apple's kerberos is installed and raise an exception (I know,
how to tell...)? The problem isn't just API inconsistencies. Apple's
project requires the use of authGSSClientClean to destroy context objects
or you end up leaking memory.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/requests/requests-kerberos/issues/76#issuecomment-254667969>,
or mute the thread

**Comment by behackett** [comment]
That's fair. In that case, requests-kerberos should use authGSSClientClean. It exists in all the forks, kerberos-sspi, and winkerberos even if it doesn't do anything in a few of them. In PyMongo I just wrap the entire kerberos dance in a try / finally with authGSSClientClean in the finally block.

**Comment by lupuswere** [comment]
Thanks so much for your reply, @behackett and @rbcarson . In my case, I think I also need kerberos for other reasons. Can I re-install kerberos and then re-install pykerberos? Will this work for importing requests-kerberos as well as other cases that only require kerberos?

**Comment by behackett** [comment]
Sadly, no. They both install a single file, kerberos.so. Whichever one you install last wins. What does kerberos have that pykerberos does not? The only things I can think of are pretty esoteric.

**Comment by justinngayan** [comment]
I know this is a super old post, but THANK YOU to @rbcarson and @behackett - I literally searched about a hundred articles for 3 solid days figuring out my kerberos win_ping issue. It ended up being both kerberos and pykerberos installed. I had to uninstall both (since just uninstalling kerberos wasn't enough) via pip uninstall kerberos pykerberos and then reinstalling only pykerberos via pip install pykerberos. Worked like a charm, thanks so much!
