### ISSUE TITLE
Negotiate/SPNEGO and NTLM requires reusing the context

### ISSUE THREAD

**Issue by segevfiner** [requests/requests-kerberos#95]
I encountered a server that will only work with Negotiate\SPNEGO since it doesn't really support Kerberos but only NTLM. But it does support Negotiate\SPNEGO that uses NTLM under the hood still allowing the use of Windows SSO.

But Negotiate\SPNEGO + NTLM doesn't work in requests_kerberos since NTLM involves multiple requests and requests_kerberos recreates the GSS context on the second request instead of reusing it.

This means that PR #89 will only work for servers that support SPNEGO and Kerberos.

The fix for this shouldn't be too diffcult and I have an idea of a quick way to fix this. But for this to have any effect we need PR #89 to be merged first of course.

**Comment by nitzmahone** [comment]
The RFC-illegal connection behavior you seek has been implemented since 0.12.0- it was necessary to implement message encryption without trashing the sequence number. However, as I mentioned on #89, it looks like you'd have to switch auth handlers anyway to use NTLM, so why not just use requests-ntlm?

**Comment by jborean93** [comment]
This library is designed solely for Kerberos auth and not NTLM. Adding in Negotiate really adds very little without support NTLM and if you need that you should look into other libraries.
